- .github/workflows/ci.yml
- cmd/refcandidates/candidates.go
- cmd/refcandidates/main.go
- go.mod
- go.sum
- vendor/github.com/sethvargo/go-githubactions/.gitignore
- vendor/github.com/sethvargo/go-githubactions/AUTHORS
- vendor/github.com/sethvargo/go-githubactions/LICENSE
- vendor/github.com/sethvargo/go-githubactions/Makefile
- vendor/github.com/sethvargo/go-githubactions/README.md
- vendor/github.com/sethvargo/go-githubactions/actions.go
- vendor/github.com/sethvargo/go-githubactions/actions_root.go
- vendor/github.com/sethvargo/go-githubactions/command.go
- vendor/github.com/sethvargo/go-githubactions/eof_crlf.go
- vendor/github.com/sethvargo/go-githubactions/eof_lf.go
- vendor/github.com/sethvargo/go-githubactions/options.go
- vendor/modules.txt
Use refcandidates tool to set github actions output that will be used as matrix input to split tests by refs instead of github-script in our workflow.
> refcandidates: set github actions output for matrix

- .github/workflows/.buildkit-binaries.yml
- .github/workflows/ci.yml
- Dockerfile
- docker-bake.hcl
In https://github.com/moby/buildkit-bench/pull/8 we were building each sandbox for a specific ref and run them also independently. This is an issue as we want to run tests for all refs within the same public GitHub Runner to avoid incorrect bench as hardware is not the same across their infrastructure.
With this change we are still building each ref on a dedicated runner to reduce build time but merge them within the sandbox. This also allows us to workaround the cache issue when using names contexts (#3).
> build each ref and merge them in tests image

- .github/workflows/ci.yml
- hack/test
- test/binary_test.go
- util/testutil/metric.go
- util/testutil/ref.go
- util/testutil/run.go
For each benchmark set ref timestamp as metric. This is to help sorting benchmarks results when merging them and generating graphs for #13.
> keep track of buildkit ref date for each benchmark

- .github/workflows/ci.yml
- util/testutil/metric.go
- util/testutil/run.go
follow-up https://github.com/moby/buildkit-bench/pull/29#issue-2494038674
Ref timestamp is just used to manage sorting of data points in generated graphs. We can do that directly during merge.
> don't report ref_timestamp as metric

- cmd/gotestmetrics/merge.go
> merge: improve data points visibility

- test/binary_test.go
relates to https://github.com/moby/buildkit-bench/actions/runs/10616869615/job/29428495239#step:7:139
```
goos: linux
goarch: amd64
pkg: github.com/moby/buildkit-bench/test
cpu: AMD EPYC 7763 64-Core Processor                
BenchmarkBinary
PASS
ok  	github.com/moby/buildkit-bench/test	0.635s
?   	github.com/moby/buildkit-bench/util/candidates	[no test files]
?   	github.com/moby/buildkit-bench/util/github	[no test files]
?   	github.com/moby/buildkit-bench/util/gotest	[no test files]
?   	github.com/moby/buildkit-bench/util/gotest/benchmark	[no test files]
?   	github.com/moby/buildkit-bench/util/testutil	[no test files]
+ docker rm -v buildkit-bench-cache
```
Benchmark didn't run, we should probably error out in this case.
> fix benchmarkPackageSize missing

- .github/workflows/ci.yml
reduce build time for test image when loading to docker store
> ci: use docker driver to build sandbox

- Dockerfile
- test/build_test.go
- test/buildx_test.go
- test/util.go
- util/testutil/ref.go
- util/testutil/run.go
- util/testutil/util.go
Use Buildx as client instead of buildctl.
As follow-up we could set `--metadata-file` https://docs.docker.com/reference/cli/docker/buildx/build/#metadata-file and `BUILDX_METADATA_PROVENANCE` to `max` so we can have details metrics we could use. This will not work for BuildKit versions that don't support history API though.
> test: switch from buildctl to buildx 0.17.0 as client

- README.md
- hack/test
- testconfig.yml
relates to https://github.com/golang/go/issues/27217#issuecomment-453829330
> test: set default benchtime to 0.01s

- docker-bake.hcl
Not sure why this was set but it can't be as only
versions starting from v0.13.0 understand this ARG.
Release binaries also do not have this enabled so
should give more consistent results with production.
> remove BUILDKIT_DEBUG from buildkit-build

- .github/workflows/ci.yml
Because no emulators are installed in kernel many codepaths are skipped and bugs in typical environment can go undetected.
Local run:
```
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=1-8         	       1	16970149777 ns/op	 2942184 B/op	    5658 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=2
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=2-8         	       1	16661650068 ns/op	 2437440 B/op	    5549 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=1
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=1-8         	       1	16414651131 ns/op	 2582616 B/op	    5552 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=2
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=2-8         	       1	16919238467 ns/op	 2694360 …
```
> github: setup-qemu for more realistic test environment

- test/build_test.go
Make sure tested codepath is longer and doesn't
end without trying to export the build result.
Local run:
```
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=1
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=1-8         	       1	80665038297 ns/op	 3005320 B/op	    5638 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=2
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.12.0/run=2-8         	       1	17462715767 ns/op	 2784432 B/op	    5266 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=1
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=1-8         	       1	19406766775 ns/op	 2808448 B/op	    5564 allocs/op
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=2
BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.13.0/run=2-8         	       1 …
```
> Enable creating image as part of the test

- README.md
- hack/test
- testconfig.yml
In some cases we have really tiny benchmark and therefore we needed to adjust benchtime to avoid the benchmark to hang as there would not have been enough iteration. Instead of using a duration we can just default to the number of iteration we want, in this case `1x`:
```
-benchtime t
Run enough iterations of each benchmark to take t, specified
as a time.Duration (for example, -benchtime 1h30s).
The default is 1 second (1s).
The special syntax Nx means to run the benchmark N times
(for example, -benchtime 100x).
```
As follow-up we can look what benchmarks need iteration adjustment.
> test: run a single iteration for benchmark by default

- .github/workflows/ci.yml
- go.mod
- test/build_test.go
- testconfig.yml
- util/testutil/ref.go
relates to https://github.com/moby/buildkit/pull/4949
> test: build with emulator

- README.md
- website/.gitignore
- website/generateResults.js
- website/src/components/ResultView.vue
- website/src/components/ResultsList.vue
- website/vue.config.js
This is to avoid XHR requests when using `fetch` so metadata are solved at build time.
> website: load result metadata at build time

- util/testutil/run.go
oversight from https://github.com/moby/buildkit-bench/pull/126
> testutil: fix bench timing

- test/build_test.go
With image export added in https://github.com/moby/buildkit-bench/pull/146#discussion_r1771580503, we are now seeing gaps for timing between runs for high parallelization build benchs:
```
$ TEST_KEEP_CACHE=1 TEST_BENCH_RUN=3 BUILDKIT_REFS=v0.9.3,v0.15.2,master TEST_BENCH_REGEXP=/BenchmarkBuildHighParallelization32x$ make bench
...
goos: linux
goarch: amd64
pkg: github.com/moby/buildkit-bench/test
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkBuild
time="2024-09-26T10:28:14Z" level=info msg="starting registry mirror"
time="2024-09-26T10:28:14Z" level=info msg="registry mirror started at localhost:45415"
BenchmarkBuild/BenchmarkBuildHighParallelization32x/ref=master/run=1
BenchmarkBuild/BenchmarkBuildHighParallelization32x/ref=master/run=1-32                        1        33208780898 …
```
> test: warmup before running high parallelization bench

- .github/workflows/regen.yml
Oversight in regen when implementing logs export when publishing
> ci: fix missing logs during regen

- .github/workflows/ci.yml
We got no space left on github runners when trying to publish: https://github.com/moby/buildkit-bench/actions/runs/12007277408/job/33491722706
Probably because of the logs so let remove unneeded tools.
> ci: free disk space when publishing

- .github/workflows/gc.yml
similar to https://github.com/moby/buildkit-bench/pull/187
relates to https://github.com/moby/buildkit-bench/actions/runs/12093057272:
> ci(gc): free disk space

- .github/workflows/ci.yml
- .github/workflows/regen.yml
- Dockerfile
- website/src/components/ResultView.vue
Publish job hangs due to large amount of logs for each result when pushing to github pages.
> gen: compress logs
