.github/workflows/ci.yml, hack/test, util/testutil/ref.go, util/testutil/run.go
relates to https://github.com/moby/buildkit-bench/pull/28
=> cleanup committer date code

cmd/gotestmetrics/merge.go
follow-up https://github.com/moby/buildkit-bench/pull/34#issue-2494659151
=> validate benchmark results against testconfig

hack/test
=> hack: add TEST_PKG var

.github/workflows/ci.yml, hack/test
Defaults to `.` to run all benchmarks.
=> hack: add TEST_BENCH_REGEXP var

.github/workflows/ci.yml, test/build_test.go, testconfig.yml
relates to https://github.com/docker/buildx/issues/2479
=> test: build with secret

cmd/gotestmetrics/gen.go
Box plot charts are currently corrupted for build breaker benchs:
```html
<div class="box">
<div class="container">
<div class="item" id="oWzEIEqOitnZ" style="width:900px;height:500px;"></div>
</div>
<script type="text/javascript">
"use strict";
let goecharts_oWzEIEqOitnZ = echarts.init(document.getElementById('oWzEIEqOitnZ'), "white", {
renderer: "canvas"
});
let option_oWzEIEqOitnZ = goecharts_oWzEIEqOitnZ.setOption(option_oWzEIEqOitnZ);
</script>
<div class="container">
<div class="item" id="GyldjNkXYhQH" style="width:900px;height:500px;"></div>
</div>
<script type="text/javascript">
"use strict";
let goecharts_GyldjNkXYhQH = echarts.init(document.getElementById('GyldjNkXYhQH'), "white", {
renderer: "canvas"
});
let option_GyldjNkXYhQH = …
```
=> charts: fix box plot data

testconfig.yml
=> test: increase build breaker runs

test/build_test.go, testconfig.yml
~needs #78 to remove reset of benchtime~
=> test: use NsPerOp as duration metric

.github/workflows/ci.yml, .github/workflows/regen.yml, Dockerfile
With #82 we can have old charts not aligned with latest framework changes. This workflow will generate archived results with latest changes.
=> ci: regen workflow to generate archived results with latest changes

test/build_test.go
relates to https://github.com/moby/buildkit-bench/actions/runs/10879938814/job/30185800093#step:7:2611
```
build_test.go:104: 
Error Trace:	/src/test/build_test.go:104
/usr/local/go/src/runtime/asm_amd64.s:1695
Error:      	Received unexpected error:
exit status 1
Test:       	BenchmarkBuild/BenchmarkBuildBreaker64/ref=v0.9.3/run=4
Messages:   	#0 building with "remote-ro8nkhgw09ltl34woc8rs06m4" instance using remote driver
#1 [internal] load git source https://github.com/dvdksn/buildme.git#eb6279e0ad8a10003718656c6867539bd9426ad8
#1 0.013 hint: Using 'master' as the name for the initial branch. This default branch name
#1 0.013 hint: is subject to change. To configure the initial branch name to use in all
#1 0.013 hint: of your new repositories, which will suppress this warning, call:
#1 …
```
=> test: mirror dockerfile image

.github/workflows/ci.yml
=> ci: add gha event json and env list to report

.github/workflows/ci.yml
=> run workflow every week

Makefile, README.md, docker-bake.hcl, hack/gen, website/Dockerfile, website/compose.yaml
=> generate html report and serve website

.github/workflows/ci.yml, README.md, hack/test, test/build_test.go, testconfig.yml
=> ci: split test and benchmark jobs

util/testutil/run.go
relates to https://github.com/moby/buildkit-bench/pull/132#issuecomment-2363655099
=> testutil: set up mirror before running tests

.github/workflows/ci.yml, docker-bake.hcl
https://github.com/moby/buildkit/pull/5342
=> add custom ref to bench gogoproto removal

website/src/components/ResultsList.vue
=> website: fix result direct link

cmd/gotestmetrics/gen.go, website/src/components/ResultView.vue
=> handle gha schedule event

.github/workflows/ci.yml
https://github.com/moby/buildkit/pull/5342 has been merged :tada:
=> candidates: remove pr-5342

website/src/App.vue
fixes #159 
https://github.com/user-attachments/assets/25b397e9-6f55-4cdc-800a-b70967a6b16f
=> website: fix missing sidebar scrollbar

.github/workflows/.benchmark.yml, .github/workflows/.binaries.yml, .github/workflows/ci.yml, .github/workflows/regen.yml, Dockerfile, README.md, cmd/gotestmetrics/gen.go, cmd/gotestmetrics/list.go, docker-bake.hcl, hack/test, test/build_test.go, test/buildx_test.go, test/daemon_test.go, test/package_test.go, test/util.go, testconfig.yml, util/gotest/benchmark.go, util/testutil/config.go, util/testutil/ref.go, util/testutil/run.go, util/testutil/sandbox.go, util/testutil/util.go, website/package.json, website/src/components/ResultView.vue, website/vue.config.js, website/yarn.lock
fixes #157 
https://github.com/user-attachments/assets/9a09cac2-e5e4-4799-b45a-256a8e622b85
=> bench buildx candidates

.github/workflows/regen.yml, Dockerfile, cmd/gotestmetrics/gen.go, docker-bake.hcl
=> charts: toolbox and markline for average

.github/workflows/gc.yml
=> ci: gc workflow

docker-bake.hcl
follow-up https://github.com/docker/buildx/pull/2649
=> bake: use sanitize func
